### ISSUE TITLE
"invalid character '<' looking for beginning of value"

### ISSUE THREAD

**Issue by myszuram** [kookehs/bdo-marketplace#1]
Am I doing something wrong?

![marketplace](https://user-images.githubusercontent.com/47323062/82318266-d8a20c00-99cf-11ea-8ed7-1f299c99540b.png)

**Comment by kookehs** [comment]
My guess is either `cookie` or `token` values are incorrect.
The API will respond with HTML for a 404 page.
Unfortunately the API responds with `200 OK` regardless..

Double check values for `cookie` and `token` from network traffic.
You can test the response with cURL or Postman.

**Comment by allannery02** [comment]
Hello how can i find the values to put in Cookie and token?

**Comment by kookehs** [comment]
You can use the developer tools provided by your browser to look at network requests for the site.

0. You may need to spoof `User-Agent` as a mobile browser. Not sure if they have removed the restriction on viewing marketplace from mobile only.
1. https://market.blackdesertonline.com/
    - Select your region and sign in.
2. Open `Developer Tools` for your browser and select `Network`.
    - For Chrome it's `Ctrl+Shift+I` and click `Network` tab.
    - For Firefox it's `Ctrl+Shift+E` to open `Network` tab.
3. Click the search icon. Search for any item.
4. Click on the listing to open up details for that item.
5. Check for a request to `GetWorldMarketSubList` in `Network` tab.
    - `cookie` is found in ` Request Headers` under `Cookie` -> `__RequestVerificationToken`.
   - `token` is found in `Form Data` under `__RequestVerificationToken`.

**Comment by kookehs** [comment]
Closing this issue given there has been no response for days now.
Feel free to open up another if this persists.
