### ISSUE TITLE
Information request

### ISSUE THREAD

**Issue by Aoize** [kookehs/bdo-marketplace#12]
Hi, 

I am just wondering what the "timeout" request is within the config.json/go file. What is its purpose and use?

**Comment by dennypenta** [comment]
Timeout is the duration when the request for the data will be closed.
For instance:
- "1s" is 1 second,
- "2m" is 2 minutes,

you can combine the digit and symbol to config timeout duration.
Official documentation:
ParseDuration parses a duration string. A duration string is a possibly signed sequence of decimal numbers, each with optional fraction and a unit suffix, such as "300ms", "-1.5h" or "2h45m". Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".

Link:
https://golang.org/pkg/time/#ParseDuration

**Comment by kookehs** [comment]
The purpose of the timeout was to ensure requests don't run forever. I believe by default no timeout is set for `http.Client`.
