### ISSUE TITLE
Ban

### ISSUE THREAD

**Issue by dennypenta** [kookehs/bdo-marketplace#13]
Good day.
Is there any case you can catch the ban in the game?
I mean they are writing some kind of metrics and it alerts on anomaly behavior of users.

**Comment by kookehs** [comment]
I have no knowledge on their ban process or criteria.
You may want to contact their support to get an official statement.
Please refer to the Terms of Service: https://www.blackdesertonline.com/legal/terms-of-use
- Sections 12.1.3 & 12.1.5 are loosely defined and is at their discretion.
