### ISSUE TITLE
ASP.NET_SessionId

### ISSUE THREAD

**Issue by vava456** [kookehs/bdo-marketplace#14]
Hi, its not an issue with the project, i was just wondering how do you bypass the ASP.NET_SessionId. Doing an api for a project i'm stuck on this, it expire and change and i don't know how you got away with this, because you use only __RequestVerificationToken and a post request need more information.

**Comment by kookehs** [comment]
> how do you bypass the ASP.NET_SessionId

I don't believe it's required for a call to their backend. The `__RequestVerificationToken` found in cookies changes from time to time, so I assume it's based off the `ASP.NET_SessionId`. I haven't looked, but if you poke around the JavaScript code a `beforeSend` may set this up.

> it expire and change

While the session may expire, it appears both the token generated from the session and form are still valid. I'm still using token from the beginning of this year. Keep in mind you'll have to use form tokens from the same session they were generated in. Both tokens contain anti-XSRF token within and must match when extracted. More on [token validation](https://docs.microsoft.com/en-us/aspnet/mvc/overview/security/xsrfcsrf-prevention-in-aspnet-mvc-and-web-pages#validating-the-tokens).

**Comment by vava456** [comment]
Thanks for the quick response,
I know the token doesn't expire often it stay the same but the asp.net_sessionid does and i can't make a request without it.
Let me be more clear, I'm making a post request on GetWorldMarketSubList for instance here is the most important part of my request in c# :
I send a POST request to : http://marketweb-eu.blackdesertonline.com/Home/GetWorldMarketSubList

request.Headers.TryAddWithoutValidation("Cookie", "ASP.NET_SessionId=asp_sess; __RequestVerificationToken=token");
request.Content = new StringContent("__RequestVerificationToken=cookie&mainKey=12031");

If i don't mention the asp.net_sessionid i get the following error : {"resultCode":2000,"resultMsg":"TRADE_MARKET_ERROR_MSG_UNAUTHORIZED","redirectUrl":"https://account.playkakaogames.com/oauth/blackdesert/authorize?client_id=bdo_central_market_web-eu-live\u0026response_type=code"}
I have to update very often the asp.net_sessionid for it to work so i don't understand how you do it, can you send me the type of request you are sending for it to work, like curl bash request for example.

I really appreciate your time and effort to help me.

**Comment by kookehs** [comment]
> request.Headers.TryAddWithoutValidation("Cookie", "ASP.NET_SessionId=asp_sess; __RequestVerificationToken=token");
request.Content = new StringContent("__RequestVerificationToken=cookie&mainKey=12031");

If there's complete minimal code to reproduce I could look into it more.

```
curl --location --request POST 'https://marketweb-eu.blackdesertonline.com/Home/GetWorldMarketSubList' \
--header 'Cookie: __RequestVerificationToken=<TOKEN>' \
--header 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36' \
--form '__RequestVerificationToken=<TOKEN>' \
--form 'mainKey=5804' \
--form 'usingCleint=0'
```

**Comment by vava456** [comment]
Hi, thanks for the reply
I have just tried your request and it doesn't work i have the same error : 

{"resultCode":2000,"resultMsg":"TRADE_MARKET_ERROR_MSG_UNAUTHORIZED","redirectUrl":"https://account.playkakaogames.com/oauth/blackdesert/authorize?client_id=bdo_central_market_web-eu-live\u0026response_type=code"}

When i don't mention asp.net_sessionid i always get this error when i mention it everything works.
Can you send me a curl that work on https://reqbin.com/curl where it return sublist info if you don't mind because i can't find a way to get around it.

Thank you by advance.

**Comment by kookehs** [comment]
> {"resultCode":2000,"resultMsg":"TRADE_MARKET_ERROR_MSG_UNAUTHORIZED","redirectUrl":"https://account.playkakaogames.com/oauth/blackdesert/authorize?client_id=bdo_central_market_web-eu-live\u0026response_type=code"}

I haven't seen this response before. I'm wondering if the backend is different for EU? I don't have an EU account to test with so can't confirm, but I don't imagine it would be different. Usually when credentials, headers, or form data is incorrect it returns a 404 page.

> Can you send me a curl that work on https://reqbin.com/curl

The above tool doesn't support form data.
Tested it here and it works. https://repl.it/repls/PrevailingHotpinkCodewarrior#main.sh

**Comment by vava456** [comment]
Thanks, i have fixed my problem thanks to you.
The issue was this curl option : "-H 'X-Requested-With: XMLHttpRequest' \" this was forcing ajax request and needed me to specify asp.net_sessionid removing it fixed everything.
Thanks for your time!
