### ISSUE TITLE
search for upgraded versions

### ISSUE THREAD

**Issue by allannery02** [kookehs/bdo-marketplace#2]
Hello,
Can it get the upgraded version prices of the itens, Pri duo tri tet?
if yes what is the configuration

**Comment by kookehs** [comment]
This is now a feature in the latest release. https://github.com/kookehs/bdo-marketplace/commit/fc15e8084871dbe9786c8e136c5b71e216bb8ead
The tool will grab all enhancement levels that can be listed on the market for each item.
It may skip some enhancement levels based on how BDO groups some levels.
