### ISSUE TITLE
Item missing & Typos

### ISSUE THREAD

**Issue by dphilpot** [kookehs/bdo-marketplace#4]
Hey,

the items.json file is missing "Savory Steak" as well as a few typos as far as i know on items:

9488
9637

**Comment by dphilpot** [comment]
#5 created pullrequest

**Comment by kookehs** [comment]
Thanks for the PR!
The file, `items.json`, is quite out of date. There are likely many more items missing.
I should probably extract the items from files again and change the format a little.
But it'll serve as a reference for people to work with for now.

**Comment by dphilpot** [comment]
Hi @kookehs, maybe you can tell me how you extracted the data?
a thought on this would also be multilingual files?

**Comment by kookehs** [comment]
The ideal way to get it is through decrypting the `*.paz` files and `*.pak` files for items and locales. There are tools out there for this. Alternative approaches are to scrape the official API or fan databases. I don't imagine people are gathering data for all items, so looking up IDs from fan databases may suffice for now.

As for supporting multiple languages that could be accomplished using an ID for I18N lookup against locales. I haven't seen the data for locals, but I assume they're already set up in such a way.

I would like to keep as much of the game's data off this repository, as to not infringe on any of their copyrights or efforts.
